# Tarea - Programación lineal

### Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en $100$ gramos, se deben tener **por lo menos** $8$ gramos de proteína y $6$ gramos de grasa. Así mismo, no se debe tener más de $2$ gramos de fibra y $0.4$ gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

Ingrediente|Proteína|Grasa|Fibra|Sal
:----|----|----|----|----
Pollo|  10.0%|08.0%|00.1%|00.2%
Carne|  20.0%|10.0%|00.5%|00.5%
Cordero|15.0%|11.0%|00.5%|00.7%
Arroz|  00.0%|01.0%|10.0%|00.2%
Trigo|  04.0%|01.0%|15.0%|00.8%
Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total. Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Gramos de pollo  
+ $x_2:$ Gramos de carne  
+ $x_3:$ Gramos de cordero  
+ $x_4:$ Gramos de arroz  
+ $x_5:$ Gramos de trigo  
+ $x_6:$ Gramos de gel

La tarea consiste en plantear el problemade programación lineal que permita satisfacer las necesidades alimenticias del gato al tiempo que minimice el costo total y resolverlo con `linprog`.

Se desea minimizar el costo total, este viene dado por la siguiente funcion


$ min 0.013x_{1} + 0.008 x_{2} + 0.01 x_{3} + 0.002 x_{4} + 0.005 x_{5} + 0.001 x_{6}  $

Teniendo en cuenta las siguientes restricciones
- En 100g de compuesto: $ x_{1} + x_{2} + x_{3} + x_{4} + x_{5} + x_{6} \leq 100  $ 
- Restriccion de la cantidad de proteina:  $ 0.1x_{1} + 0.2 x_{2} + 0.15 x_{3} +  + 0.04 x_{5} \geq 8  $
- Restriccion de la cantidad de grasa: $ 0.08x_{1} + 0.1 x_{2} + 0.11 x_{3} + 0.01 x_{4} + 0.01 x_{5} \geq 6  $
- Restriccion de la cantidad de fibra: $ 0.001x_{1} + 0.005 x_{2} + 0.005 x_{3} + 0.1 x_{4} + 0.15 x_{5} \leq 2  $
- Restriccion de la cantidad de sal: $ 0.002x_{1} + 0.005 x_{2} + 0.007 x_{3} + 0.002 x_{4} + 0.008 x_{5} \leq 0.4  $

Con ayuda de esto nos es posible plantear nuestras matrices

In [5]:
import numpy as np
import scipy.optimize as opt #Libreria para optimizar

c=np.array([-0.013,-0.008,-0.01,-0.002,-0.005,-0.001]) #Matriz a minimizar
a=np.array([[1,1,1,1,1,1],
            [-0.1,-0.2,-0.15,0,-0.04,0],
            [-0.08,-0.1,-0.11,-0.001,-0.01,0],
            [0.001,0.005,0.005,0.1,0.15,0],
            [0.002,0.005,0.007,0.002,0.008,0]]) #Matriz de coeficientes

b=np.array([100,-8,-6,2,0.4]) # Matriz de resultados

respuesta1=opt.linprog(c,a,b,method="simplex")
respuesta1.x

array([100.,   0.,   0.,   0.,   0.,   0.])

Ya con las cantidades optimizadas provamos las restricciones

In [3]:
lista1=[]
for i in range (len(a)):
    suma=0
    for j in range(len(a[i])):
        suma+=a[i][j]*respuesta1.x[j]
    lista1.append(suma)
lista1

[100.0, -10.0, -8.0, 0.1, 0.2]

Aunque algo extraña la ultima, podemos notar las restricciones se cumple por lo que consideraremos estas cantidades como correctas

### Problema de distribución de energía eléctrica

La Comisión Federal de Electricidad **(CFE)** dispone de tres plantas de generación para satisfacer la demanda diaria eléctrica en tres ciudades; Guadalajara, León y Morelia. Las plantas $1$, $2$ y $3$ pueden satisfacer $80$, $40$ y $60$ millones de KW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de $70$, $40$ y $70$ millones de Kw al día respectivamente. 


Los costos asociados al envío de suministro energético por cada millón de Kw entre cada planta y cada ciudad son los registrados en la siguiente tabla. 

-|Guadalajara|León|Morelia
:----|----|----|----
Planta 1|5|2|7
Planta 2|3|6|6
Planta 3|6|1|2

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada planta (en millones de KW) y cada ciudad.

Para simplificar la notación use las siguientes variables:

+ $x_1$: Kw (en millones) distribuidos de la Planta 1 a Guadalajara
+ $x_2$: Kw (en millones) distribuidos de la Planta 1 a León
+ $x_3$: Kw (en millones) distribuidos de la Planta 1 a Morelia
+ $x_4$: Kw (en millones) distribuidos de la Planta 2 a Guadalajara
+ $x_5$: Kw (en millones) distribuidos de la Planta 2 a León
+ $x_6$: Kw (en millones) distribuidos de la Planta 2 a Morelia
+ $x_7$: Kw (en millones) distribuidos de la Planta 3 a Guadalajara
+ $x_8$: Kw (en millones) distribuidos de la Planta 3 a León
+ $x_9$: Kw (en millones) distribuidos de la Planta 3 a Morelia

La tarea consiste en plantear el problema de programación lineal que permita satisfacer las necesidades de todas las ciudades al tiempo que minimice los costos asociados a la distribución y resolverlo con `linprog`.

Se desea minimizar el costo de distribucion total, este viene dado por la siguiente funcion


$ min 5x_{1} + 2x_{2} + 7x_{3} +3x_{4} + 6x_{5} + 6x_{6} + 6x_{7} + x_{8} + 2x_{9}  $

Teniendo en cuenta las siguientes restricciones
- Capacidad de la planta 1: $ x_{1} + x_{2} + x_{3} \leq 80  $ 
- Capacidad de la planta 2: $ x_{4} + x_{5} + x_{6} \leq 40  $ 
- Capacidad de la planta 3: $ x_{7} + x_{8} + x_{9} \leq 60  $ 
- Nececidad de la ciudad de Guadalajara:  $ x_{1} + x_{4} + x_{7} \geq 70  $
- Nececidad de la ciudad de Leon:  $ x_{2} + x_{5} + x_{8} \geq 40  $
- Nececidad de la ciudad de Morelia:  $ x_{3} + x_{6} + x_{9} \geq 70  $

Con ayuda de esto nos es posible plantear nuestras matrices

In [6]:
c2=np.array([5,2,7,3,6,6,6,1,2]) #Matriz a minimizar
a2=np.array([[1,1,1,0,0,0,0,0,0],
            [0,0,0,1,1,1,0,0,0],
            [0,0,0,0,0,0,1,1,1],
            [-1,0,0,-1,0,0,-1,0,0],
            [0,-1,0,0,-1,0,0,-1,0],
            [0,0,-1,0,0,-1,0,0,-1]]) #Matriz de coeficientes

b2=np.array([80,40,60,-70,-40,-70]) # Matriz de resultados

respuesta2=opt.linprog(c2,a2,b2, method="simplex")
respuesta2.x

array([30., 40., 10., 40.,  0.,  0.,  0.,  0., 60.])

Ya con las cantidades optimizadas provemos las restricciones

In [7]:
lista2=[]
for i in range (len(a2)):
    suma=0
    for j in range(len(a2[i])):
        suma+=a2[i][j]*respuesta2.x[j]
    lista2.append(suma)
lista2

[80.0, 40.0, 60.0, -70.0, -40.0, -70.0]

Como podemos notar las restriccion se cumplen por lo que consideraremos estas cantidades como correctas

## Ejercicio en clase - Lunes 14 de febrero

El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más from IPython.display import YouTubeVideo
YouTubeVideo('gukxBus8lOs')de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Este problema puede ser resuelto con programación lineal. Formalmente, puede ser descrito como:

$$\max_{A_1,A_2,...,A_6}\sum^{6}_{i=1} A_iR_i,$$

donde $A_i$ representa la cantidad invertida en la opción, y $R_i$ representa la tasa de retorno respectiva.

Nuestra funcion a minimizar es
$ 0.0865A_{1} + 0.095A_{2} + 0.1A_{3} + 0.0875A_{4} + 0.0925A_{5} + 0.09A_{6} $

Ahora planteamos las restricciones
- Cantidad máxima de dinero a invertir: $A_{1} + A_{2} + A_{3} +A_{4} + A_{5} + A_{6} \leq 750000 $
- La mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez: $ A_{1} + A_{2} + A_{4} + A_{6} \geq 375000 $ #Esta debe ser negativa
- Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono: $  A_{1} \leq 187500 , A_{2} \leq 187500 , A_{3} \leq 187500, A_{4} \leq 187500, A_{5} \leq 187500, A_{6} \leq 187500 $
- No permite usar más de $35\%$ en bonos de alto riesgo: $ A_{2} + A_{3} + A_{5} \leq 262500 $

Con ayuda de estas restricciones planteamos nuestras matrices

In [1]:
import numpy as np
import scipy.optimize as opt #Libreria para optimizar

c=np.array([-0.0865,-0.095,-0.1,-0.0875,-0.0925,-0.09]) #Matriz a minimizar
a3=np.array([[1,1,1,1,1,1],
            [-1,-1,0,-1,0,-1],
            [1,0,0,0,0,0],
            [0,1,0,0,0,0],
            [0,0,1,0,0,0],
            [0,0,0,1,0,0],
            [0,0,0,0,1,0],
            [0,0,0,0,0,1],
            [0,1,1,0,1,0]]) #Matriz de coeficientes

b=np.array([750000,-375000,187500,187500,187500,187500,187500,187500,262500]) # Matriz de resultados

respuesta3=opt.linprog(c,a3,b, method="simplex")
respuesta3.x

array([112500.,  75000., 187500., 187500.,      0., 187500.])

Probamos nuestras restricciones

In [2]:
lista3=[]
for i in range (len(a3)):
    suma=0
    for j in range(len(a3[i])):
        suma+=a3[i][j]*respuesta3.x[j]
    lista3.append(suma)
lista3

[750000.0,
 -562500.0,
 112500.0,
 75000.0,
 187500.0,
 187500.0,
 0.0,
 187500.0,
 262500.0]

Podemos notar que si se cumplen por lo que consideraremos estos valores como ciertos